2025-04-07 20:59:34,304 INFO    StreamThr :1332309 [internal.py:wandb_internal():85] W&B internal server running at pid: 1332309, started at: 2025-04-07 20:59:34.295822
2025-04-07 20:59:34,306 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status
2025-04-07 20:59:34,321 INFO    WriterThread:1332309 [datastore.py:open_for_write():87] open: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/run-bfcmw573.wandb
2025-04-07 20:59:34,331 DEBUG   SenderThread:1332309 [sender.py:send():379] send: header
2025-04-07 20:59:34,604 DEBUG   SenderThread:1332309 [sender.py:send():379] send: run
2025-04-07 20:59:35,076 INFO    SenderThread:1332309 [dir_watcher.py:__init__():211] watching files in: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files
2025-04-07 20:59:35,076 INFO    SenderThread:1332309 [sender.py:_start_run_threads():1188] run started: bfcmw573 with start time 1744052374.316064
2025-04-07 20:59:35,141 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: check_version
2025-04-07 20:59:35,142 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: check_version
2025-04-07 20:59:35,237 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: run_start
2025-04-07 20:59:36,017 DEBUG   HandlerThread:1332309 [system_info.py:__init__():26] System info init
2025-04-07 20:59:36,017 DEBUG   HandlerThread:1332309 [system_info.py:__init__():41] System info init done
2025-04-07 20:59:36,017 INFO    HandlerThread:1332309 [system_monitor.py:start():194] Starting system monitor
2025-04-07 20:59:36,018 INFO    SystemMonitor:1332309 [system_monitor.py:_start():158] Starting system asset monitoring threads
2025-04-07 20:59:36,018 INFO    HandlerThread:1332309 [system_monitor.py:probe():214] Collecting system info
2025-04-07 20:59:36,049 INFO    SystemMonitor:1332309 [interfaces.py:start():188] Started cpu monitoring
2025-04-07 20:59:36,054 INFO    SystemMonitor:1332309 [interfaces.py:start():188] Started disk monitoring
2025-04-07 20:59:36,054 INFO    SystemMonitor:1332309 [interfaces.py:start():188] Started gpu monitoring
2025-04-07 20:59:36,058 INFO    SystemMonitor:1332309 [interfaces.py:start():188] Started memory monitoring
2025-04-07 20:59:36,059 INFO    SystemMonitor:1332309 [interfaces.py:start():188] Started network monitoring
2025-04-07 20:59:36,087 DEBUG   HandlerThread:1332309 [system_info.py:probe():152] Probing system
2025-04-07 20:59:36,124 DEBUG   HandlerThread:1332309 [system_info.py:_probe_git():137] Probing git
2025-04-07 20:59:36,308 DEBUG   HandlerThread:1332309 [system_info.py:_probe_git():145] Probing git done
2025-04-07 20:59:36,308 DEBUG   HandlerThread:1332309 [system_info.py:probe():200] Probing system done
2025-04-07 20:59:36,308 DEBUG   HandlerThread:1332309 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-131-generic-x86_64-with-glibc2.35', 'python': '3.11.6', 'heartbeatAt': '2025-04-07T18:59:36.087922', 'startedAt': '2025-04-07T18:59:34.178449', 'docker': None, 'cuda': None, 'args': ('--dataset', 'UnconditionalSeismic3D', '--model_type', 'PreconditionedDenoiser3D', '--save_dir', 'GenCFD/outputs/UnconditionalSeismic3D-2', '--num_train_steps', '5000000', '--worker', '4', '--batch_size', '8', '--track_memory'), 'state': 'running', 'program': '-m GenCFD.train.train_gencfd', 'codePathLocal': None, 'git': {'remote': 'https://github.com/LuisCarretero/GenCFD.git', 'commit': '7ff7fb7bbc95817b317583c33e6ab301b6e83491'}, 'email': 'luis.carretero@gmx.de', 'root': '/cluster/home/lcarretero/workspace/rds/GenCFD', 'host': 'eu-lo-g3-014', 'username': 'lcarretero', 'executable': '/cluster/home/lcarretero/python_envs/rds-misc/bin/python3', 'cpu_count': 128, 'cpu_count_logical': 128, 'cpu_freq': {'current': 1960.3931093750002, 'min': 1500.0, 'max': 2250.0}, 'cpu_freq_per_core': [{'current': 1685.351, 'min': 1500.0, 'max': 2250.0}, {'current': 3397.317, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 3396.688, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 3395.89, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 3388.927, 'min': 1500.0, 'max': 2250.0}, {'current': 3388.302, 'min': 1500.0, 'max': 2250.0}, {'current': 3388.995, 'min': 1500.0, 'max': 2250.0}, {'current': 3388.742, 'min': 1500.0, 'max': 2250.0}, {'current': 3389.746, 'min': 1500.0, 'max': 2250.0}, {'current': 2743.334, 'min': 1500.0, 'max': 2250.0}, {'current': 3389.554, 'min': 1500.0, 'max': 2250.0}, {'current': 2672.858, 'min': 1500.0, 'max': 2250.0}, {'current': 3390.354, 'min': 1500.0, 'max': 2250.0}, {'current': 3390.463, 'min': 1500.0, 'max': 2250.0}, {'current': 3390.455, 'min': 1500.0, 'max': 2250.0}, {'current': 2632.261, 'min': 1500.0, 'max': 2250.0}, {'current': 3390.655, 'min': 1500.0, 'max': 2250.0}, {'current': 2250.0, 'min': 1500.0, 'max': 2250.0}, {'current': 3390.509, 'min': 1500.0, 'max': 2250.0}, {'current': 3389.454, 'min': 1500.0, 'max': 2250.0}, {'current': 3396.598, 'min': 1500.0, 'max': 2250.0}, {'current': 3396.188, 'min': 1500.0, 'max': 2250.0}, {'current': 3396.512, 'min': 1500.0, 'max': 2250.0}, {'current': 3396.576, 'min': 1500.0, 'max': 2250.0}, {'current': 3390.499, 'min': 1500.0, 'max': 2250.0}, {'current': 2731.821, 'min': 1500.0, 'max': 2250.0}, {'current': 3390.739, 'min': 1500.0, 'max': 2250.0}, {'current': 3284.296, 'min': 1500.0, 'max': 2250.0}, {'current': 3391.14, 'min': 1500.0, 'max': 2250.0}, {'current': 2250.0, 'min': 1500.0, 'max': 2250.0}, {'current': 3391.182, 'min': 1500.0, 'max': 2250.0}, {'current': 2741.638, 'min': 1500.0, 'max': 2250.0}, {'current': 3388.046, 'min': 1500.0, 'max': 2250.0}, {'current': 2250.0, 'min': 1500.0, 'max': 2250.0}, {'current': 3388.123, 'min': 1500.0, 'max': 2250.0}, {'current': 3387.831, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}, {'current': 1500.0, 'min': 1500.0, 'max': 2250.0}], 'disk': {'/': {'total': 10.0, 'used': 7.213996887207031}}, 'gpu': 'NVIDIA GeForce RTX 2080 Ti', 'gpu_count': 4, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 2080 Ti', 'memory_total': 11811160064}, {'name': 'NVIDIA GeForce RTX 2080 Ti', 'memory_total': 11811160064}, {'name': 'NVIDIA GeForce RTX 2080 Ti', 'memory_total': 11811160064}, {'name': 'NVIDIA GeForce RTX 2080 Ti', 'memory_total': 11811160064}], 'memory': {'total': 501.45680236816406}}
2025-04-07 20:59:36,309 INFO    HandlerThread:1332309 [system_monitor.py:probe():224] Finished collecting system info
2025-04-07 20:59:36,309 INFO    HandlerThread:1332309 [system_monitor.py:probe():227] Publishing system info
2025-04-07 20:59:36,328 INFO    HandlerThread:1332309 [system_monitor.py:probe():229] Finished publishing system info
2025-04-07 20:59:36,416 DEBUG   SenderThread:1332309 [sender.py:send():379] send: files
2025-04-07 20:59:36,416 INFO    SenderThread:1332309 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2025-04-07 20:59:36,705 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89c55690>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 20:59:36,705 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15453'}
2025-04-07 20:59:36,705 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 20:59:37,091 INFO    Thread-12 :1332309 [dir_watcher.py:_on_file_created():271] file/dir created: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files/wandb-metadata.json
2025-04-07 20:59:37,936 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89c09ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 20:59:37,936 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15453'}
2025-04-07 20:59:37,936 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 20:59:39,417 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 20:59:40,309 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89c30ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 20:59:40,309 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15453'}
2025-04-07 20:59:40,309 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 20:59:40,309 INFO    wandb-upload_0:1332309 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connection.py", line 211, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x149b89c30ad0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89c30ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2840, in upload_file
    response = self._upload_file_session.put(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89c30ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2871, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2840, in upload_file
    response = self._upload_file_session.put(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2025-04-07 20:59:41,022 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: python_packages
2025-04-07 20:59:41,022 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: python_packages
2025-04-07 20:59:41,023 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 20:59:41,025 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:41,036 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 20:59:41,119 INFO    Thread-12 :1332309 [dir_watcher.py:_on_file_created():271] file/dir created: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files/requirements.txt
2025-04-07 20:59:41,280 DEBUG   SenderThread:1332309 [sender.py:send():379] send: telemetry
2025-04-07 20:59:42,023 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:43,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:44,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:44,137 INFO    Thread-12 :1332309 [dir_watcher.py:_on_file_created():271] file/dir created: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files/output.log
2025-04-07 20:59:45,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:45,127 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 20:59:45,169 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b53d8bd50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 20:59:45,169 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15453'}
2025-04-07 20:59:45,169 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 20:59:46,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:46,150 INFO    Thread-12 :1332309 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files/output.log
2025-04-07 20:59:47,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:48,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:49,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:50,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:51,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 20:59:51,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:52,025 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:53,025 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:53,457 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b53dbe310>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 20:59:53,457 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15453'}
2025-04-07 20:59:53,457 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 20:59:54,025 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:55,025 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:56,023 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 20:59:56,023 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 20:59:56,065 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:56,251 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 20:59:57,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:58,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 20:59:59,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:00,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:01,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:02,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:02,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:03,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:04,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:05,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:06,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:07,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:08,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:08,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:09,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:10,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:10,307 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b53d8ad50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:00:10,307 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15453'}
2025-04-07 21:00:10,307 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:00:11,023 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:00:11,023 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:00:11,069 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:11,314 INFO    Thread-12 :1332309 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files/config.yaml
2025-04-07 21:00:12,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:13,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:14,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:15,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:16,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:16,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:17,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:18,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:19,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:20,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:21,024 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:21,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:22,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:23,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:24,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:25,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:26,023 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:00:26,023 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:00:26,065 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:26,274 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:27,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:28,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:29,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:30,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:31,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:32,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:32,032 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:33,032 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:34,032 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:35,033 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:36,033 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:36,059 DEBUG   SystemMonitor:1332309 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2025-04-07 21:00:36,063 DEBUG   SenderThread:1332309 [sender.py:send():379] send: stats
2025-04-07 21:00:37,034 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:37,065 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:38,034 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:39,034 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:40,034 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:41,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:00:41,028 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:00:41,069 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:42,034 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:42,302 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:43,034 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:43,283 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89c33750>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:00:43,283 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15453'}
2025-04-07 21:00:43,283 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:00:44,034 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:45,034 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:46,035 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:47,035 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:48,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:48,035 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:49,035 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:50,035 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:51,035 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:52,035 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:53,037 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:54,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:00:54,037 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:55,037 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:56,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:00:56,029 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:00:56,069 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:57,038 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:58,038 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:59,234 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:00:59,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:00,234 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:01,234 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:02,235 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:03,235 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:04,236 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:05,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:05,235 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:06,067 DEBUG   SenderThread:1332309 [sender.py:send():379] send: stats
2025-04-07 21:01:06,235 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:07,241 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:08,241 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:09,241 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:10,070 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:10,241 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:11,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:01:11,028 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:01:11,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:12,241 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:13,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:14,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:15,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:15,244 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:16,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:17,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:18,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:19,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:20,243 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:21,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:21,242 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:22,243 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:23,243 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:24,243 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:25,244 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:26,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:01:26,028 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:01:26,236 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:26,243 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:27,244 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:28,244 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:29,244 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:30,244 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:31,244 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:32,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:32,244 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:33,244 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:34,245 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:35,245 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:36,070 DEBUG   SenderThread:1332309 [sender.py:send():379] send: stats
2025-04-07 21:01:36,245 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:37,073 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:37,245 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:38,245 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:39,245 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:40,245 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:41,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:01:41,028 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:01:41,245 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:42,246 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:42,294 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:43,246 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:44,246 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:45,246 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:46,246 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:47,246 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:48,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:48,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:49,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:50,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:51,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:52,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:53,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:53,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:54,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:55,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:56,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:01:56,028 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:01:56,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:56,393 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b53dbf1d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:01:56,393 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15453'}
2025-04-07 21:01:56,393 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:01:57,248 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:58,224 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:01:58,248 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:01:59,248 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:00,248 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:01,248 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:02,248 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:03,248 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:04,032 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:04,249 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:05,249 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:06,074 DEBUG   SenderThread:1332309 [sender.py:send():379] send: stats
2025-04-07 21:02:06,249 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:07,249 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:08,253 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:09,076 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:09,253 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:10,253 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:11,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:02:11,029 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:02:11,253 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:12,254 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:13,254 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:14,254 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:14,262 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:15,254 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:16,254 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:17,254 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:18,254 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:19,255 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:20,036 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:20,255 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:21,255 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:22,255 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:23,255 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:24,255 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:25,036 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:25,255 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:26,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:02:26,029 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:02:26,422 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:27,421 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:28,422 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:29,421 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:30,271 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:30,421 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:31,425 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:32,426 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:33,426 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:34,426 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:35,426 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:36,036 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:36,076 DEBUG   SenderThread:1332309 [sender.py:send():379] send: stats
2025-04-07 21:02:36,426 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:37,426 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:38,426 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:39,426 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:40,428 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:41,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:02:41,029 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:02:41,274 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:41,428 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:42,428 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:43,429 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:44,429 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:45,429 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:46,430 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:47,036 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:47,430 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:48,430 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:49,430 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:50,430 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:51,430 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:52,430 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:53,037 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:53,431 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:54,431 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:55,453 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:56,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:02:56,029 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:02:56,453 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:57,453 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:58,210 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:02:58,453 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:02:59,453 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:00,453 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:01,453 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:02,454 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:03,454 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:04,037 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:03:04,454 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:05,454 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:06,080 DEBUG   SenderThread:1332309 [sender.py:send():379] send: stats
2025-04-07 21:03:06,454 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:07,454 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:08,454 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:09,082 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:03:09,454 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:10,455 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:11,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:03:11,030 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:03:11,455 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:12,455 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:13,455 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:14,278 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:03:14,455 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:15,455 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:16,455 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:17,455 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:18,456 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:19,456 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:20,038 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:03:20,456 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:21,457 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:22,456 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:23,456 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:24,457 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:25,457 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:26,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:03:26,030 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:03:26,255 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:03:26,459 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:27,459 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:28,459 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:29,460 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:30,460 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:31,460 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:32,038 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:03:32,460 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:33,461 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:34,461 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:35,461 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:36,088 DEBUG   SenderThread:1332309 [sender.py:send():379] send: stats
2025-04-07 21:03:36,461 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:37,090 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:03:37,461 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:38,461 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:39,461 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:40,461 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:41,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:03:41,030 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:03:41,462 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:42,236 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:03:42,463 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:43,463 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:44,463 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:45,463 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:46,463 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:47,463 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:48,038 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:03:48,463 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:49,464 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:50,464 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:51,464 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:52,464 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:53,464 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:54,038 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:03:54,464 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:55,464 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:56,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:03:56,030 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:03:56,464 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:57,465 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:58,465 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:03:59,291 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:03:59,465 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:00,465 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:01,465 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:02,465 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:03,465 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:04,465 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:05,039 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:04:05,466 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:06,087 DEBUG   SenderThread:1332309 [sender.py:send():379] send: stats
2025-04-07 21:04:06,466 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:07,466 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:08,466 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:09,466 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:10,089 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:04:10,466 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:11,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:04:11,030 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:04:11,466 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:12,466 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:13,466 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:14,467 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:15,251 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:04:15,467 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:16,467 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:17,468 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:18,467 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:19,467 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:20,468 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:21,039 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:04:21,468 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:22,468 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:23,468 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:24,468 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:25,468 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:26,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:04:26,030 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:04:26,217 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:04:26,468 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:27,469 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:28,545 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:29,546 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:29,943 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-metadata.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T185936Z&X-Goog-Expires=86399&X-Goog-Signature=9eb803d7664ed44e682336143ac3261e586b414dad23fd15b5c911093d070c712e3818f5ae1d1361ae33c33f84267d928271594f89706e002c288e63f494e02f7c5567876e2991aa6019fd1b06371586e65d63d2be99ffbc5a4037380968b18d53cf9c7859ffc6289cc74333bc183ecce49be9ae979a0b9ed63f7f01795dcb6f7df6974ee9bf591d41b711314a7b0693e658a4b63bc3cdaad0c1d334b0b104e6f441fb980a992d9c5f71e5826e61ce1af0544e159af72de0d6e3f0f1115cf7a4cfdd39abf415b88e76cd3aab127ea6a91237a5193fdb8de9a215e2e41b321bbf32e936f9a740946b4b8ae52fc6127b95a2db93261b9fb5fbc7449622f2df9f12&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89bb7890>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:04:29,943 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15453'}
2025-04-07 21:04:29,943 ERROR   wandb-upload_0:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:04:30,545 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:31,545 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:32,039 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:04:32,545 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:33,545 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:34,545 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:35,545 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:36,091 DEBUG   SenderThread:1332309 [sender.py:send():379] send: stats
2025-04-07 21:04:36,546 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:37,093 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:04:37,546 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:38,546 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:39,546 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:40,546 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:41,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:04:41,030 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:04:41,546 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:42,205 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:04:42,546 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:43,547 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:44,546 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:45,549 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:46,549 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:47,549 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:48,040 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:04:48,550 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:49,550 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:50,550 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:51,550 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:52,550 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:53,040 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:04:53,550 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:54,550 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:55,551 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:56,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:04:56,030 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:04:56,550 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:57,551 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:58,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:04:58,551 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:04:59,551 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:00,551 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:01,551 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:02,551 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:03,552 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:04,040 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:05:04,552 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:05,552 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:06,094 DEBUG   SenderThread:1332309 [sender.py:send():379] send: stats
2025-04-07 21:05:06,552 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:07,552 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:08,552 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:09,096 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:05:09,552 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:10,552 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:11,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:05:11,030 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:05:11,552 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:12,553 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:13,553 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:14,260 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:05:14,553 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:15,553 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:16,554 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:17,554 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:18,554 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:19,554 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:20,041 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:05:20,555 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:21,554 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:22,555 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:23,556 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:24,556 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:25,041 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:05:25,556 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:26,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:05:26,030 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:05:26,632 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:27,632 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:28,632 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:29,632 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:30,290 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:05:30,632 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:31,632 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:32,633 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:33,633 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:34,633 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:35,633 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:36,042 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:05:36,098 DEBUG   SenderThread:1332309 [sender.py:send():379] send: stats
2025-04-07 21:05:36,633 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:37,633 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:38,633 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:39,633 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:40,634 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:41,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:05:41,031 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:05:41,292 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:05:41,634 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:42,634 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:43,634 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:44,634 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:45,634 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:46,634 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:47,043 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:05:47,634 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:48,634 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:49,635 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:50,635 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:51,635 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:52,635 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:53,043 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:05:53,635 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:54,635 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:55,635 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:56,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: stop_status
2025-04-07 21:05:56,031 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: stop_status
2025-04-07 21:05:56,635 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: internal_messages
2025-04-07 21:05:57,025 DEBUG   SenderThread:1332309 [sender.py:send():379] send: exit
2025-04-07 21:05:57,025 INFO    SenderThread:1332309 [sender.py:send_exit():586] handling exit code: 1
2025-04-07 21:05:57,025 INFO    SenderThread:1332309 [sender.py:send_exit():588] handling runtime: 381
2025-04-07 21:05:57,038 INFO    SenderThread:1332309 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2025-04-07 21:05:57,039 INFO    SenderThread:1332309 [sender.py:send_exit():594] send defer
2025-04-07 21:05:57,039 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: defer
2025-04-07 21:05:57,039 INFO    HandlerThread:1332309 [handler.py:handle_request_defer():184] handle defer: 0
2025-04-07 21:05:57,039 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: defer
2025-04-07 21:05:57,039 INFO    SenderThread:1332309 [sender.py:send_request_defer():610] handle sender defer: 0
2025-04-07 21:05:57,039 INFO    SenderThread:1332309 [sender.py:transition_state():614] send defer: 1
2025-04-07 21:05:57,039 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: defer
2025-04-07 21:05:57,040 INFO    HandlerThread:1332309 [handler.py:handle_request_defer():184] handle defer: 1
2025-04-07 21:05:57,040 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: defer
2025-04-07 21:05:57,040 INFO    SenderThread:1332309 [sender.py:send_request_defer():610] handle sender defer: 1
2025-04-07 21:05:57,040 INFO    SenderThread:1332309 [sender.py:transition_state():614] send defer: 2
2025-04-07 21:05:57,040 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: defer
2025-04-07 21:05:57,040 INFO    HandlerThread:1332309 [handler.py:handle_request_defer():184] handle defer: 2
2025-04-07 21:05:57,040 INFO    HandlerThread:1332309 [system_monitor.py:finish():203] Stopping system monitor
2025-04-07 21:05:57,042 INFO    HandlerThread:1332309 [interfaces.py:finish():200] Joined cpu monitor
2025-04-07 21:05:57,042 INFO    HandlerThread:1332309 [interfaces.py:finish():200] Joined disk monitor
2025-04-07 21:05:57,043 DEBUG   SystemMonitor:1332309 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2025-04-07 21:05:57,043 DEBUG   SystemMonitor:1332309 [system_monitor.py:_start():183] Publishing last batch of metrics
2025-04-07 21:05:57,140 INFO    Thread-12 :1332309 [dir_watcher.py:_on_file_created():271] file/dir created: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files/wandb-summary.json
2025-04-07 21:05:57,966 INFO    HandlerThread:1332309 [interfaces.py:finish():200] Joined gpu monitor
2025-04-07 21:05:57,967 INFO    HandlerThread:1332309 [interfaces.py:finish():200] Joined memory monitor
2025-04-07 21:05:57,967 INFO    HandlerThread:1332309 [interfaces.py:finish():200] Joined network monitor
2025-04-07 21:05:57,968 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: defer
2025-04-07 21:05:57,968 INFO    SenderThread:1332309 [sender.py:send_request_defer():610] handle sender defer: 2
2025-04-07 21:05:57,968 INFO    SenderThread:1332309 [sender.py:transition_state():614] send defer: 3
2025-04-07 21:05:57,968 DEBUG   SenderThread:1332309 [sender.py:send():379] send: stats
2025-04-07 21:05:57,970 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: defer
2025-04-07 21:05:57,970 INFO    HandlerThread:1332309 [handler.py:handle_request_defer():184] handle defer: 3
2025-04-07 21:05:57,970 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: defer
2025-04-07 21:05:57,971 INFO    SenderThread:1332309 [sender.py:send_request_defer():610] handle sender defer: 3
2025-04-07 21:05:57,971 INFO    SenderThread:1332309 [sender.py:transition_state():614] send defer: 4
2025-04-07 21:05:57,971 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: defer
2025-04-07 21:05:57,971 INFO    HandlerThread:1332309 [handler.py:handle_request_defer():184] handle defer: 4
2025-04-07 21:05:57,971 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: defer
2025-04-07 21:05:57,971 INFO    SenderThread:1332309 [sender.py:send_request_defer():610] handle sender defer: 4
2025-04-07 21:05:57,971 INFO    SenderThread:1332309 [sender.py:transition_state():614] send defer: 5
2025-04-07 21:05:57,972 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: defer
2025-04-07 21:05:57,972 INFO    HandlerThread:1332309 [handler.py:handle_request_defer():184] handle defer: 5
2025-04-07 21:05:57,972 DEBUG   SenderThread:1332309 [sender.py:send():379] send: summary
2025-04-07 21:05:57,989 INFO    SenderThread:1332309 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2025-04-07 21:05:57,990 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: defer
2025-04-07 21:05:57,990 INFO    SenderThread:1332309 [sender.py:send_request_defer():610] handle sender defer: 5
2025-04-07 21:05:57,990 INFO    SenderThread:1332309 [sender.py:transition_state():614] send defer: 6
2025-04-07 21:05:57,990 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: defer
2025-04-07 21:05:57,990 INFO    HandlerThread:1332309 [handler.py:handle_request_defer():184] handle defer: 6
2025-04-07 21:05:57,990 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: defer
2025-04-07 21:05:57,990 INFO    SenderThread:1332309 [sender.py:send_request_defer():610] handle sender defer: 6
2025-04-07 21:05:57,991 INFO    SenderThread:1332309 [sender.py:transition_state():614] send defer: 7
2025-04-07 21:05:57,991 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:05:57,991 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: defer
2025-04-07 21:05:57,991 INFO    HandlerThread:1332309 [handler.py:handle_request_defer():184] handle defer: 7
2025-04-07 21:05:57,991 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: defer
2025-04-07 21:05:57,991 INFO    SenderThread:1332309 [sender.py:send_request_defer():610] handle sender defer: 7
2025-04-07 21:05:58,025 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:05:58,144 INFO    Thread-12 :1332309 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files/wandb-summary.json
2025-04-07 21:05:58,240 INFO    SenderThread:1332309 [sender.py:transition_state():614] send defer: 8
2025-04-07 21:05:58,241 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:05:58,241 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: defer
2025-04-07 21:05:58,241 INFO    HandlerThread:1332309 [handler.py:handle_request_defer():184] handle defer: 8
2025-04-07 21:05:58,242 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: defer
2025-04-07 21:05:58,242 INFO    SenderThread:1332309 [sender.py:send_request_defer():610] handle sender defer: 8
2025-04-07 21:05:58,242 INFO    SenderThread:1332309 [job_builder.py:build():440] Attempting to build job artifact
2025-04-07 21:05:58,247 INFO    SenderThread:1332309 [job_builder.py:_get_source_type():569] is repo sourced job
2025-04-07 21:05:58,247 WARNING SenderThread:1332309 [job_builder.py:_log_if_verbose():274] No program path found, not creating job artifact. See https://docs.wandb.ai/guides/launch/create-job
2025-04-07 21:05:58,247 INFO    SenderThread:1332309 [sender.py:transition_state():614] send defer: 9
2025-04-07 21:05:58,247 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: defer
2025-04-07 21:05:58,247 INFO    HandlerThread:1332309 [handler.py:handle_request_defer():184] handle defer: 9
2025-04-07 21:05:58,248 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: defer
2025-04-07 21:05:58,248 INFO    SenderThread:1332309 [sender.py:send_request_defer():610] handle sender defer: 9
2025-04-07 21:05:58,248 INFO    SenderThread:1332309 [dir_watcher.py:finish():358] shutting down directory watcher
2025-04-07 21:05:59,025 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:05:59,153 INFO    SenderThread:1332309 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files/output.log
2025-04-07 21:05:59,153 INFO    SenderThread:1332309 [dir_watcher.py:finish():388] scan: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files
2025-04-07 21:05:59,158 INFO    SenderThread:1332309 [dir_watcher.py:finish():402] scan save: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files/config.yaml config.yaml
2025-04-07 21:05:59,158 INFO    SenderThread:1332309 [dir_watcher.py:finish():402] scan save: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files/wandb-metadata.json wandb-metadata.json
2025-04-07 21:05:59,158 INFO    SenderThread:1332309 [dir_watcher.py:finish():402] scan save: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files/requirements.txt requirements.txt
2025-04-07 21:05:59,158 INFO    SenderThread:1332309 [dir_watcher.py:finish():402] scan save: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files/output.log output.log
2025-04-07 21:05:59,164 INFO    SenderThread:1332309 [dir_watcher.py:finish():402] scan save: /cluster/home/lcarretero/workspace/rds/GenCFD/wandb/run-20250407_205934-bfcmw573/files/wandb-summary.json wandb-summary.json
2025-04-07 21:05:59,168 INFO    SenderThread:1332309 [sender.py:transition_state():614] send defer: 10
2025-04-07 21:05:59,169 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:05:59,169 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: defer
2025-04-07 21:05:59,169 INFO    HandlerThread:1332309 [handler.py:handle_request_defer():184] handle defer: 10
2025-04-07 21:05:59,176 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: defer
2025-04-07 21:05:59,176 INFO    SenderThread:1332309 [sender.py:send_request_defer():610] handle sender defer: 10
2025-04-07 21:05:59,176 INFO    SenderThread:1332309 [file_pusher.py:finish():169] shutting down file pusher
2025-04-07 21:05:59,318 ERROR   wandb-upload_1:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/config.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=1575f6873e1b3be5bd22d64d91ac342f2287d3525ed073a353547af9e14e6a20ca1cf782af3b7a6fcdf4d8944fc6510a48617c7a6cfa624fc98cc25cfb91bb5cc3044c94383fae2d95c84b84a105019b028b1304e91c63bcba41749a1bb43784502fba0450d06b27cd81375a67d85bbe34e44acec19723dd1ffaff3f321f3f43ebddcc7f8a8d16b93c22a76302ca76d2d0c62d58891166d0ec1caead72ff2119743809cdf7aea6bba1b1ff67e9ab6ee5a355fb1004e6f565c3b1148121a229cb6fe2b5162876c446e00fb0148899ff3d9d586f3e4197fc2f19f153decf45304a0032e5bb7290ea366531839db857b5aa457939ae26332bbba4a97eba6dd023b1&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/config.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=1575f6873e1b3be5bd22d64d91ac342f2287d3525ed073a353547af9e14e6a20ca1cf782af3b7a6fcdf4d8944fc6510a48617c7a6cfa624fc98cc25cfb91bb5cc3044c94383fae2d95c84b84a105019b028b1304e91c63bcba41749a1bb43784502fba0450d06b27cd81375a67d85bbe34e44acec19723dd1ffaff3f321f3f43ebddcc7f8a8d16b93c22a76302ca76d2d0c62d58891166d0ec1caead72ff2119743809cdf7aea6bba1b1ff67e9ab6ee5a355fb1004e6f565c3b1148121a229cb6fe2b5162876c446e00fb0148899ff3d9d586f3e4197fc2f19f153decf45304a0032e5bb7290ea366531839db857b5aa457939ae26332bbba4a97eba6dd023b1&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89c55f90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:05:59,318 ERROR   wandb-upload_1:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2460'}
2025-04-07 21:05:59,318 ERROR   wandb-upload_1:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:05:59,338 ERROR   wandb-upload_2:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/requirements.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=225efac809eea3eda4a41c57b391208bbaae3f2ae41e41ea0ce5fe209d21696acfa4ff467c1a346113a732eb012b7457be9db0be4cb517742450a7a38d0c64c93eff43b489a66ce879558c882624410571bf7b40a45b890f87696b17f511695991880fb134d43ddd0b073ac4825a753f81628dcb01968ebadc81d1b982392972443f1ac57981e1b1a1cd197539939570b1b66bb6c52cb1955e26c5e39153b92b2057dda4fb0119f7292128e793d0c37c5fefc42b9d62f75eb8b1322f1975aa33f35adf45b63c41cbe7c0b2e6f839415ba2a4c4911fd880b0c85f53ab4a0bd41ad7ca14a5c76bd3b402a8056382b09ebe7d576a9e0729ee4034495f16e300b294&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/requirements.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=225efac809eea3eda4a41c57b391208bbaae3f2ae41e41ea0ce5fe209d21696acfa4ff467c1a346113a732eb012b7457be9db0be4cb517742450a7a38d0c64c93eff43b489a66ce879558c882624410571bf7b40a45b890f87696b17f511695991880fb134d43ddd0b073ac4825a753f81628dcb01968ebadc81d1b982392972443f1ac57981e1b1a1cd197539939570b1b66bb6c52cb1955e26c5e39153b92b2057dda4fb0119f7292128e793d0c37c5fefc42b9d62f75eb8b1322f1975aa33f35adf45b63c41cbe7c0b2e6f839415ba2a4c4911fd880b0c85f53ab4a0bd41ad7ca14a5c76bd3b402a8056382b09ebe7d576a9e0729ee4034495f16e300b294&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89c33d50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:05:59,338 ERROR   wandb-upload_2:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6791'}
2025-04-07 21:05:59,338 ERROR   wandb-upload_2:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:05:59,371 ERROR   wandb-upload_4:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-summary.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=bc6ba65a0658a77690b542821dafea5ef38127a3cf46334d5089d3c0e9374c042abbca52c3323ca7f0451e29da1fcb82a3db3898a522789482d8feca6a92ebb8546cf9e47d4a51e16481b43d84e84a54e6450e90d6a04dc74b4d9f19748ccc269c0acec48bc3e735f908417406d3108bca73af6b01f811d15204e53d57909ca6a8841bd7cdade88afa2d3a66f64e9391aa482e3ec9a81b3926e2f11300568be9e8ab7056d8f58d9bc37f0f4e854edede671b7be54e9d5699ad0642bdc4d37851a20940ff3fe6ce817c3f4ad29064d61b24a7fa9134881624f5f73d2ca94a1d4e6848cd72c2d218bbe5f8ce1069f700590b744eea387ecf4c819476ebe5d575ed&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-summary.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=bc6ba65a0658a77690b542821dafea5ef38127a3cf46334d5089d3c0e9374c042abbca52c3323ca7f0451e29da1fcb82a3db3898a522789482d8feca6a92ebb8546cf9e47d4a51e16481b43d84e84a54e6450e90d6a04dc74b4d9f19748ccc269c0acec48bc3e735f908417406d3108bca73af6b01f811d15204e53d57909ca6a8841bd7cdade88afa2d3a66f64e9391aa482e3ec9a81b3926e2f11300568be9e8ab7056d8f58d9bc37f0f4e854edede671b7be54e9d5699ad0642bdc4d37851a20940ff3fe6ce817c3f4ad29064d61b24a7fa9134881624f5f73d2ca94a1d4e6848cd72c2d218bbe5f8ce1069f700590b744eea387ecf4c819476ebe5d575ed&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b53df2c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:05:59,372 ERROR   wandb-upload_4:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '28'}
2025-04-07 21:05:59,372 ERROR   wandb-upload_4:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:05:59,376 ERROR   wandb-upload_3:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/output.log?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=24eb4c9fc320948f627062372cbd21890115580d40d5675aa252ea01633098c59efd337a5479c0f79b37765aefdba1fccd6a08f0634ccd2796fd00d8dde139686ac64f4a4377ec0a0b891a0aeca87534b08bf6fccc84c1ffd2fa71b2292fe0932dfebb848a641fb796935b31c7273ff8853fab0e4fb3ec41925714925eb4bdd39978ad67027f4a224015a6da56e932c4cc96de7010f38aa2e50450db0a3428dfe6f9c6eebbb8e72274355938840588425a0ed1c53d717ba0c33ab30000a1afc610379574f4e34f93e4ed6a50fea25888ff902e5dd608a3adba48a4ff3dfdeed6e288676384816b641099b7e01177bbd8504074928e7fbde97950fba0d6b5eac9&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/output.log?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=24eb4c9fc320948f627062372cbd21890115580d40d5675aa252ea01633098c59efd337a5479c0f79b37765aefdba1fccd6a08f0634ccd2796fd00d8dde139686ac64f4a4377ec0a0b891a0aeca87534b08bf6fccc84c1ffd2fa71b2292fe0932dfebb848a641fb796935b31c7273ff8853fab0e4fb3ec41925714925eb4bdd39978ad67027f4a224015a6da56e932c4cc96de7010f38aa2e50450db0a3428dfe6f9c6eebbb8e72274355938840588425a0ed1c53d717ba0c33ab30000a1afc610379574f4e34f93e4ed6a50fea25888ff902e5dd608a3adba48a4ff3dfdeed6e288676384816b641099b7e01177bbd8504074928e7fbde97950fba0d6b5eac9&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b53df3d50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:05:59,376 ERROR   wandb-upload_3:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2025-04-07 21:05:59,376 ERROR   wandb-upload_3:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:06:00,026 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:00,027 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:00,449 ERROR   wandb-upload_1:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/config.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=1575f6873e1b3be5bd22d64d91ac342f2287d3525ed073a353547af9e14e6a20ca1cf782af3b7a6fcdf4d8944fc6510a48617c7a6cfa624fc98cc25cfb91bb5cc3044c94383fae2d95c84b84a105019b028b1304e91c63bcba41749a1bb43784502fba0450d06b27cd81375a67d85bbe34e44acec19723dd1ffaff3f321f3f43ebddcc7f8a8d16b93c22a76302ca76d2d0c62d58891166d0ec1caead72ff2119743809cdf7aea6bba1b1ff67e9ab6ee5a355fb1004e6f565c3b1148121a229cb6fe2b5162876c446e00fb0148899ff3d9d586f3e4197fc2f19f153decf45304a0032e5bb7290ea366531839db857b5aa457939ae26332bbba4a97eba6dd023b1&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/config.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=1575f6873e1b3be5bd22d64d91ac342f2287d3525ed073a353547af9e14e6a20ca1cf782af3b7a6fcdf4d8944fc6510a48617c7a6cfa624fc98cc25cfb91bb5cc3044c94383fae2d95c84b84a105019b028b1304e91c63bcba41749a1bb43784502fba0450d06b27cd81375a67d85bbe34e44acec19723dd1ffaff3f321f3f43ebddcc7f8a8d16b93c22a76302ca76d2d0c62d58891166d0ec1caead72ff2119743809cdf7aea6bba1b1ff67e9ab6ee5a355fb1004e6f565c3b1148121a229cb6fe2b5162876c446e00fb0148899ff3d9d586f3e4197fc2f19f153decf45304a0032e5bb7290ea366531839db857b5aa457939ae26332bbba4a97eba6dd023b1&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89bd5450>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:06:00,449 ERROR   wandb-upload_1:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2460'}
2025-04-07 21:06:00,449 ERROR   wandb-upload_1:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:06:00,486 ERROR   wandb-upload_3:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/output.log?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=24eb4c9fc320948f627062372cbd21890115580d40d5675aa252ea01633098c59efd337a5479c0f79b37765aefdba1fccd6a08f0634ccd2796fd00d8dde139686ac64f4a4377ec0a0b891a0aeca87534b08bf6fccc84c1ffd2fa71b2292fe0932dfebb848a641fb796935b31c7273ff8853fab0e4fb3ec41925714925eb4bdd39978ad67027f4a224015a6da56e932c4cc96de7010f38aa2e50450db0a3428dfe6f9c6eebbb8e72274355938840588425a0ed1c53d717ba0c33ab30000a1afc610379574f4e34f93e4ed6a50fea25888ff902e5dd608a3adba48a4ff3dfdeed6e288676384816b641099b7e01177bbd8504074928e7fbde97950fba0d6b5eac9&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/output.log?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=24eb4c9fc320948f627062372cbd21890115580d40d5675aa252ea01633098c59efd337a5479c0f79b37765aefdba1fccd6a08f0634ccd2796fd00d8dde139686ac64f4a4377ec0a0b891a0aeca87534b08bf6fccc84c1ffd2fa71b2292fe0932dfebb848a641fb796935b31c7273ff8853fab0e4fb3ec41925714925eb4bdd39978ad67027f4a224015a6da56e932c4cc96de7010f38aa2e50450db0a3428dfe6f9c6eebbb8e72274355938840588425a0ed1c53d717ba0c33ab30000a1afc610379574f4e34f93e4ed6a50fea25888ff902e5dd608a3adba48a4ff3dfdeed6e288676384816b641099b7e01177bbd8504074928e7fbde97950fba0d6b5eac9&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89bdee10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:06:00,486 ERROR   wandb-upload_3:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2025-04-07 21:06:00,486 ERROR   wandb-upload_3:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:06:00,487 INFO    wandb-upload_3:1332309 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connection.py", line 211, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x149b89bdee10>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/output.log?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=24eb4c9fc320948f627062372cbd21890115580d40d5675aa252ea01633098c59efd337a5479c0f79b37765aefdba1fccd6a08f0634ccd2796fd00d8dde139686ac64f4a4377ec0a0b891a0aeca87534b08bf6fccc84c1ffd2fa71b2292fe0932dfebb848a641fb796935b31c7273ff8853fab0e4fb3ec41925714925eb4bdd39978ad67027f4a224015a6da56e932c4cc96de7010f38aa2e50450db0a3428dfe6f9c6eebbb8e72274355938840588425a0ed1c53d717ba0c33ab30000a1afc610379574f4e34f93e4ed6a50fea25888ff902e5dd608a3adba48a4ff3dfdeed6e288676384816b641099b7e01177bbd8504074928e7fbde97950fba0d6b5eac9&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89bdee10>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2840, in upload_file
    response = self._upload_file_session.put(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/output.log?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=24eb4c9fc320948f627062372cbd21890115580d40d5675aa252ea01633098c59efd337a5479c0f79b37765aefdba1fccd6a08f0634ccd2796fd00d8dde139686ac64f4a4377ec0a0b891a0aeca87534b08bf6fccc84c1ffd2fa71b2292fe0932dfebb848a641fb796935b31c7273ff8853fab0e4fb3ec41925714925eb4bdd39978ad67027f4a224015a6da56e932c4cc96de7010f38aa2e50450db0a3428dfe6f9c6eebbb8e72274355938840588425a0ed1c53d717ba0c33ab30000a1afc610379574f4e34f93e4ed6a50fea25888ff902e5dd608a3adba48a4ff3dfdeed6e288676384816b641099b7e01177bbd8504074928e7fbde97950fba0d6b5eac9&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89bdee10>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2871, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2840, in upload_file
    response = self._upload_file_session.put(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-06/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-12.2.0/python-3.11.6-ukhwpjnwzzzizek3pgr75zkbhxros5fq/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2025-04-07 21:06:00,511 ERROR   wandb-upload_2:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/requirements.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=225efac809eea3eda4a41c57b391208bbaae3f2ae41e41ea0ce5fe209d21696acfa4ff467c1a346113a732eb012b7457be9db0be4cb517742450a7a38d0c64c93eff43b489a66ce879558c882624410571bf7b40a45b890f87696b17f511695991880fb134d43ddd0b073ac4825a753f81628dcb01968ebadc81d1b982392972443f1ac57981e1b1a1cd197539939570b1b66bb6c52cb1955e26c5e39153b92b2057dda4fb0119f7292128e793d0c37c5fefc42b9d62f75eb8b1322f1975aa33f35adf45b63c41cbe7c0b2e6f839415ba2a4c4911fd880b0c85f53ab4a0bd41ad7ca14a5c76bd3b402a8056382b09ebe7d576a9e0729ee4034495f16e300b294&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/requirements.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=225efac809eea3eda4a41c57b391208bbaae3f2ae41e41ea0ce5fe209d21696acfa4ff467c1a346113a732eb012b7457be9db0be4cb517742450a7a38d0c64c93eff43b489a66ce879558c882624410571bf7b40a45b890f87696b17f511695991880fb134d43ddd0b073ac4825a753f81628dcb01968ebadc81d1b982392972443f1ac57981e1b1a1cd197539939570b1b66bb6c52cb1955e26c5e39153b92b2057dda4fb0119f7292128e793d0c37c5fefc42b9d62f75eb8b1322f1975aa33f35adf45b63c41cbe7c0b2e6f839415ba2a4c4911fd880b0c85f53ab4a0bd41ad7ca14a5c76bd3b402a8056382b09ebe7d576a9e0729ee4034495f16e300b294&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b53de22d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:06:00,543 ERROR   wandb-upload_2:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6791'}
2025-04-07 21:06:00,543 ERROR   wandb-upload_2:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:06:00,628 ERROR   wandb-upload_4:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-summary.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=bc6ba65a0658a77690b542821dafea5ef38127a3cf46334d5089d3c0e9374c042abbca52c3323ca7f0451e29da1fcb82a3db3898a522789482d8feca6a92ebb8546cf9e47d4a51e16481b43d84e84a54e6450e90d6a04dc74b4d9f19748ccc269c0acec48bc3e735f908417406d3108bca73af6b01f811d15204e53d57909ca6a8841bd7cdade88afa2d3a66f64e9391aa482e3ec9a81b3926e2f11300568be9e8ab7056d8f58d9bc37f0f4e854edede671b7be54e9d5699ad0642bdc4d37851a20940ff3fe6ce817c3f4ad29064d61b24a7fa9134881624f5f73d2ca94a1d4e6848cd72c2d218bbe5f8ce1069f700590b744eea387ecf4c819476ebe5d575ed&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-summary.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=bc6ba65a0658a77690b542821dafea5ef38127a3cf46334d5089d3c0e9374c042abbca52c3323ca7f0451e29da1fcb82a3db3898a522789482d8feca6a92ebb8546cf9e47d4a51e16481b43d84e84a54e6450e90d6a04dc74b4d9f19748ccc269c0acec48bc3e735f908417406d3108bca73af6b01f811d15204e53d57909ca6a8841bd7cdade88afa2d3a66f64e9391aa482e3ec9a81b3926e2f11300568be9e8ab7056d8f58d9bc37f0f4e854edede671b7be54e9d5699ad0642bdc4d37851a20940ff3fe6ce817c3f4ad29064d61b24a7fa9134881624f5f73d2ca94a1d4e6848cd72c2d218bbe5f8ce1069f700590b744eea387ecf4c819476ebe5d575ed&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b53de2d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:06:00,628 ERROR   wandb-upload_4:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '28'}
2025-04-07 21:06:00,629 ERROR   wandb-upload_4:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:06:01,027 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:01,028 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:02,028 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:02,029 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:02,579 ERROR   wandb-upload_2:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/requirements.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=225efac809eea3eda4a41c57b391208bbaae3f2ae41e41ea0ce5fe209d21696acfa4ff467c1a346113a732eb012b7457be9db0be4cb517742450a7a38d0c64c93eff43b489a66ce879558c882624410571bf7b40a45b890f87696b17f511695991880fb134d43ddd0b073ac4825a753f81628dcb01968ebadc81d1b982392972443f1ac57981e1b1a1cd197539939570b1b66bb6c52cb1955e26c5e39153b92b2057dda4fb0119f7292128e793d0c37c5fefc42b9d62f75eb8b1322f1975aa33f35adf45b63c41cbe7c0b2e6f839415ba2a4c4911fd880b0c85f53ab4a0bd41ad7ca14a5c76bd3b402a8056382b09ebe7d576a9e0729ee4034495f16e300b294&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/requirements.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=225efac809eea3eda4a41c57b391208bbaae3f2ae41e41ea0ce5fe209d21696acfa4ff467c1a346113a732eb012b7457be9db0be4cb517742450a7a38d0c64c93eff43b489a66ce879558c882624410571bf7b40a45b890f87696b17f511695991880fb134d43ddd0b073ac4825a753f81628dcb01968ebadc81d1b982392972443f1ac57981e1b1a1cd197539939570b1b66bb6c52cb1955e26c5e39153b92b2057dda4fb0119f7292128e793d0c37c5fefc42b9d62f75eb8b1322f1975aa33f35adf45b63c41cbe7c0b2e6f839415ba2a4c4911fd880b0c85f53ab4a0bd41ad7ca14a5c76bd3b402a8056382b09ebe7d576a9e0729ee4034495f16e300b294&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b53decbd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:06:02,579 ERROR   wandb-upload_2:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6791'}
2025-04-07 21:06:02,580 ERROR   wandb-upload_2:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:06:02,619 ERROR   wandb-upload_1:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/config.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=1575f6873e1b3be5bd22d64d91ac342f2287d3525ed073a353547af9e14e6a20ca1cf782af3b7a6fcdf4d8944fc6510a48617c7a6cfa624fc98cc25cfb91bb5cc3044c94383fae2d95c84b84a105019b028b1304e91c63bcba41749a1bb43784502fba0450d06b27cd81375a67d85bbe34e44acec19723dd1ffaff3f321f3f43ebddcc7f8a8d16b93c22a76302ca76d2d0c62d58891166d0ec1caead72ff2119743809cdf7aea6bba1b1ff67e9ab6ee5a355fb1004e6f565c3b1148121a229cb6fe2b5162876c446e00fb0148899ff3d9d586f3e4197fc2f19f153decf45304a0032e5bb7290ea366531839db857b5aa457939ae26332bbba4a97eba6dd023b1&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/config.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=1575f6873e1b3be5bd22d64d91ac342f2287d3525ed073a353547af9e14e6a20ca1cf782af3b7a6fcdf4d8944fc6510a48617c7a6cfa624fc98cc25cfb91bb5cc3044c94383fae2d95c84b84a105019b028b1304e91c63bcba41749a1bb43784502fba0450d06b27cd81375a67d85bbe34e44acec19723dd1ffaff3f321f3f43ebddcc7f8a8d16b93c22a76302ca76d2d0c62d58891166d0ec1caead72ff2119743809cdf7aea6bba1b1ff67e9ab6ee5a355fb1004e6f565c3b1148121a229cb6fe2b5162876c446e00fb0148899ff3d9d586f3e4197fc2f19f153decf45304a0032e5bb7290ea366531839db857b5aa457939ae26332bbba4a97eba6dd023b1&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b53def410>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:06:02,619 ERROR   wandb-upload_1:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2460'}
2025-04-07 21:06:02,619 ERROR   wandb-upload_1:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:06:03,019 ERROR   wandb-upload_4:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-summary.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=bc6ba65a0658a77690b542821dafea5ef38127a3cf46334d5089d3c0e9374c042abbca52c3323ca7f0451e29da1fcb82a3db3898a522789482d8feca6a92ebb8546cf9e47d4a51e16481b43d84e84a54e6450e90d6a04dc74b4d9f19748ccc269c0acec48bc3e735f908417406d3108bca73af6b01f811d15204e53d57909ca6a8841bd7cdade88afa2d3a66f64e9391aa482e3ec9a81b3926e2f11300568be9e8ab7056d8f58d9bc37f0f4e854edede671b7be54e9d5699ad0642bdc4d37851a20940ff3fe6ce817c3f4ad29064d61b24a7fa9134881624f5f73d2ca94a1d4e6848cd72c2d218bbe5f8ce1069f700590b744eea387ecf4c819476ebe5d575ed&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-summary.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=bc6ba65a0658a77690b542821dafea5ef38127a3cf46334d5089d3c0e9374c042abbca52c3323ca7f0451e29da1fcb82a3db3898a522789482d8feca6a92ebb8546cf9e47d4a51e16481b43d84e84a54e6450e90d6a04dc74b4d9f19748ccc269c0acec48bc3e735f908417406d3108bca73af6b01f811d15204e53d57909ca6a8841bd7cdade88afa2d3a66f64e9391aa482e3ec9a81b3926e2f11300568be9e8ab7056d8f58d9bc37f0f4e854edede671b7be54e9d5699ad0642bdc4d37851a20940ff3fe6ce817c3f4ad29064d61b24a7fa9134881624f5f73d2ca94a1d4e6848cd72c2d218bbe5f8ce1069f700590b744eea387ecf4c819476ebe5d575ed&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b51920610>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:06:03,019 ERROR   wandb-upload_4:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '28'}
2025-04-07 21:06:03,019 ERROR   wandb-upload_4:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:06:03,029 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:03,030 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:03,052 ERROR   wandb-upload_3:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/output.log?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=24eb4c9fc320948f627062372cbd21890115580d40d5675aa252ea01633098c59efd337a5479c0f79b37765aefdba1fccd6a08f0634ccd2796fd00d8dde139686ac64f4a4377ec0a0b891a0aeca87534b08bf6fccc84c1ffd2fa71b2292fe0932dfebb848a641fb796935b31c7273ff8853fab0e4fb3ec41925714925eb4bdd39978ad67027f4a224015a6da56e932c4cc96de7010f38aa2e50450db0a3428dfe6f9c6eebbb8e72274355938840588425a0ed1c53d717ba0c33ab30000a1afc610379574f4e34f93e4ed6a50fea25888ff902e5dd608a3adba48a4ff3dfdeed6e288676384816b641099b7e01177bbd8504074928e7fbde97950fba0d6b5eac9&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/output.log?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=24eb4c9fc320948f627062372cbd21890115580d40d5675aa252ea01633098c59efd337a5479c0f79b37765aefdba1fccd6a08f0634ccd2796fd00d8dde139686ac64f4a4377ec0a0b891a0aeca87534b08bf6fccc84c1ffd2fa71b2292fe0932dfebb848a641fb796935b31c7273ff8853fab0e4fb3ec41925714925eb4bdd39978ad67027f4a224015a6da56e932c4cc96de7010f38aa2e50450db0a3428dfe6f9c6eebbb8e72274355938840588425a0ed1c53d717ba0c33ab30000a1afc610379574f4e34f93e4ed6a50fea25888ff902e5dd608a3adba48a4ff3dfdeed6e288676384816b641099b7e01177bbd8504074928e7fbde97950fba0d6b5eac9&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b53def190>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:06:03,052 ERROR   wandb-upload_3:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2025-04-07 21:06:03,053 ERROR   wandb-upload_3:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:06:04,030 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:06:04,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:04,031 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:05,031 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:05,032 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:06,032 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:06,033 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:07,033 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:07,033 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:07,212 ERROR   wandb-upload_1:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/config.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=1575f6873e1b3be5bd22d64d91ac342f2287d3525ed073a353547af9e14e6a20ca1cf782af3b7a6fcdf4d8944fc6510a48617c7a6cfa624fc98cc25cfb91bb5cc3044c94383fae2d95c84b84a105019b028b1304e91c63bcba41749a1bb43784502fba0450d06b27cd81375a67d85bbe34e44acec19723dd1ffaff3f321f3f43ebddcc7f8a8d16b93c22a76302ca76d2d0c62d58891166d0ec1caead72ff2119743809cdf7aea6bba1b1ff67e9ab6ee5a355fb1004e6f565c3b1148121a229cb6fe2b5162876c446e00fb0148899ff3d9d586f3e4197fc2f19f153decf45304a0032e5bb7290ea366531839db857b5aa457939ae26332bbba4a97eba6dd023b1&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/config.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=1575f6873e1b3be5bd22d64d91ac342f2287d3525ed073a353547af9e14e6a20ca1cf782af3b7a6fcdf4d8944fc6510a48617c7a6cfa624fc98cc25cfb91bb5cc3044c94383fae2d95c84b84a105019b028b1304e91c63bcba41749a1bb43784502fba0450d06b27cd81375a67d85bbe34e44acec19723dd1ffaff3f321f3f43ebddcc7f8a8d16b93c22a76302ca76d2d0c62d58891166d0ec1caead72ff2119743809cdf7aea6bba1b1ff67e9ab6ee5a355fb1004e6f565c3b1148121a229cb6fe2b5162876c446e00fb0148899ff3d9d586f3e4197fc2f19f153decf45304a0032e5bb7290ea366531839db857b5aa457939ae26332bbba4a97eba6dd023b1&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b53dec750>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:06:07,212 ERROR   wandb-upload_1:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2460'}
2025-04-07 21:06:07,212 ERROR   wandb-upload_1:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:06:07,257 ERROR   wandb-upload_4:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-summary.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=bc6ba65a0658a77690b542821dafea5ef38127a3cf46334d5089d3c0e9374c042abbca52c3323ca7f0451e29da1fcb82a3db3898a522789482d8feca6a92ebb8546cf9e47d4a51e16481b43d84e84a54e6450e90d6a04dc74b4d9f19748ccc269c0acec48bc3e735f908417406d3108bca73af6b01f811d15204e53d57909ca6a8841bd7cdade88afa2d3a66f64e9391aa482e3ec9a81b3926e2f11300568be9e8ab7056d8f58d9bc37f0f4e854edede671b7be54e9d5699ad0642bdc4d37851a20940ff3fe6ce817c3f4ad29064d61b24a7fa9134881624f5f73d2ca94a1d4e6848cd72c2d218bbe5f8ce1069f700590b744eea387ecf4c819476ebe5d575ed&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-summary.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=bc6ba65a0658a77690b542821dafea5ef38127a3cf46334d5089d3c0e9374c042abbca52c3323ca7f0451e29da1fcb82a3db3898a522789482d8feca6a92ebb8546cf9e47d4a51e16481b43d84e84a54e6450e90d6a04dc74b4d9f19748ccc269c0acec48bc3e735f908417406d3108bca73af6b01f811d15204e53d57909ca6a8841bd7cdade88afa2d3a66f64e9391aa482e3ec9a81b3926e2f11300568be9e8ab7056d8f58d9bc37f0f4e854edede671b7be54e9d5699ad0642bdc4d37851a20940ff3fe6ce817c3f4ad29064d61b24a7fa9134881624f5f73d2ca94a1d4e6848cd72c2d218bbe5f8ce1069f700590b744eea387ecf4c819476ebe5d575ed&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89bde810>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:06:07,257 ERROR   wandb-upload_4:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '28'}
2025-04-07 21:06:07,257 ERROR   wandb-upload_4:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:06:07,364 ERROR   wandb-upload_2:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/requirements.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=225efac809eea3eda4a41c57b391208bbaae3f2ae41e41ea0ce5fe209d21696acfa4ff467c1a346113a732eb012b7457be9db0be4cb517742450a7a38d0c64c93eff43b489a66ce879558c882624410571bf7b40a45b890f87696b17f511695991880fb134d43ddd0b073ac4825a753f81628dcb01968ebadc81d1b982392972443f1ac57981e1b1a1cd197539939570b1b66bb6c52cb1955e26c5e39153b92b2057dda4fb0119f7292128e793d0c37c5fefc42b9d62f75eb8b1322f1975aa33f35adf45b63c41cbe7c0b2e6f839415ba2a4c4911fd880b0c85f53ab4a0bd41ad7ca14a5c76bd3b402a8056382b09ebe7d576a9e0729ee4034495f16e300b294&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/requirements.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=225efac809eea3eda4a41c57b391208bbaae3f2ae41e41ea0ce5fe209d21696acfa4ff467c1a346113a732eb012b7457be9db0be4cb517742450a7a38d0c64c93eff43b489a66ce879558c882624410571bf7b40a45b890f87696b17f511695991880fb134d43ddd0b073ac4825a753f81628dcb01968ebadc81d1b982392972443f1ac57981e1b1a1cd197539939570b1b66bb6c52cb1955e26c5e39153b92b2057dda4fb0119f7292128e793d0c37c5fefc42b9d62f75eb8b1322f1975aa33f35adf45b63c41cbe7c0b2e6f839415ba2a4c4911fd880b0c85f53ab4a0bd41ad7ca14a5c76bd3b402a8056382b09ebe7d576a9e0729ee4034495f16e300b294&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b53dbef90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:06:07,364 ERROR   wandb-upload_2:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6791'}
2025-04-07 21:06:07,364 ERROR   wandb-upload_2:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:06:07,439 ERROR   wandb-upload_3:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/output.log?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=24eb4c9fc320948f627062372cbd21890115580d40d5675aa252ea01633098c59efd337a5479c0f79b37765aefdba1fccd6a08f0634ccd2796fd00d8dde139686ac64f4a4377ec0a0b891a0aeca87534b08bf6fccc84c1ffd2fa71b2292fe0932dfebb848a641fb796935b31c7273ff8853fab0e4fb3ec41925714925eb4bdd39978ad67027f4a224015a6da56e932c4cc96de7010f38aa2e50450db0a3428dfe6f9c6eebbb8e72274355938840588425a0ed1c53d717ba0c33ab30000a1afc610379574f4e34f93e4ed6a50fea25888ff902e5dd608a3adba48a4ff3dfdeed6e288676384816b641099b7e01177bbd8504074928e7fbde97950fba0d6b5eac9&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/output.log?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=24eb4c9fc320948f627062372cbd21890115580d40d5675aa252ea01633098c59efd337a5479c0f79b37765aefdba1fccd6a08f0634ccd2796fd00d8dde139686ac64f4a4377ec0a0b891a0aeca87534b08bf6fccc84c1ffd2fa71b2292fe0932dfebb848a641fb796935b31c7273ff8853fab0e4fb3ec41925714925eb4bdd39978ad67027f4a224015a6da56e932c4cc96de7010f38aa2e50450db0a3428dfe6f9c6eebbb8e72274355938840588425a0ed1c53d717ba0c33ab30000a1afc610379574f4e34f93e4ed6a50fea25888ff902e5dd608a3adba48a4ff3dfdeed6e288676384816b641099b7e01177bbd8504074928e7fbde97950fba0d6b5eac9&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b53de1710>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:06:07,439 ERROR   wandb-upload_3:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2025-04-07 21:06:07,439 ERROR   wandb-upload_3:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:06:08,034 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:08,035 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:09,035 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:09,036 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:09,036 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:06:10,036 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:10,036 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:11,036 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:11,037 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:12,037 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:12,038 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:13,038 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:13,039 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:14,039 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:14,039 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:06:14,040 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:15,039 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:15,040 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:15,894 ERROR   wandb-upload_4:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-summary.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=bc6ba65a0658a77690b542821dafea5ef38127a3cf46334d5089d3c0e9374c042abbca52c3323ca7f0451e29da1fcb82a3db3898a522789482d8feca6a92ebb8546cf9e47d4a51e16481b43d84e84a54e6450e90d6a04dc74b4d9f19748ccc269c0acec48bc3e735f908417406d3108bca73af6b01f811d15204e53d57909ca6a8841bd7cdade88afa2d3a66f64e9391aa482e3ec9a81b3926e2f11300568be9e8ab7056d8f58d9bc37f0f4e854edede671b7be54e9d5699ad0642bdc4d37851a20940ff3fe6ce817c3f4ad29064d61b24a7fa9134881624f5f73d2ca94a1d4e6848cd72c2d218bbe5f8ce1069f700590b744eea387ecf4c819476ebe5d575ed&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/wandb-summary.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=bc6ba65a0658a77690b542821dafea5ef38127a3cf46334d5089d3c0e9374c042abbca52c3323ca7f0451e29da1fcb82a3db3898a522789482d8feca6a92ebb8546cf9e47d4a51e16481b43d84e84a54e6450e90d6a04dc74b4d9f19748ccc269c0acec48bc3e735f908417406d3108bca73af6b01f811d15204e53d57909ca6a8841bd7cdade88afa2d3a66f64e9391aa482e3ec9a81b3926e2f11300568be9e8ab7056d8f58d9bc37f0f4e854edede671b7be54e9d5699ad0642bdc4d37851a20940ff3fe6ce817c3f4ad29064d61b24a7fa9134881624f5f73d2ca94a1d4e6848cd72c2d218bbe5f8ce1069f700590b744eea387ecf4c819476ebe5d575ed&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b89bb7890>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:06:15,894 ERROR   wandb-upload_4:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '28'}
2025-04-07 21:06:15,894 ERROR   wandb-upload_4:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:06:16,040 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:16,041 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:16,118 ERROR   wandb-upload_1:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/config.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=1575f6873e1b3be5bd22d64d91ac342f2287d3525ed073a353547af9e14e6a20ca1cf782af3b7a6fcdf4d8944fc6510a48617c7a6cfa624fc98cc25cfb91bb5cc3044c94383fae2d95c84b84a105019b028b1304e91c63bcba41749a1bb43784502fba0450d06b27cd81375a67d85bbe34e44acec19723dd1ffaff3f321f3f43ebddcc7f8a8d16b93c22a76302ca76d2d0c62d58891166d0ec1caead72ff2119743809cdf7aea6bba1b1ff67e9ab6ee5a355fb1004e6f565c3b1148121a229cb6fe2b5162876c446e00fb0148899ff3d9d586f3e4197fc2f19f153decf45304a0032e5bb7290ea366531839db857b5aa457939ae26332bbba4a97eba6dd023b1&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/config.yaml?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=1575f6873e1b3be5bd22d64d91ac342f2287d3525ed073a353547af9e14e6a20ca1cf782af3b7a6fcdf4d8944fc6510a48617c7a6cfa624fc98cc25cfb91bb5cc3044c94383fae2d95c84b84a105019b028b1304e91c63bcba41749a1bb43784502fba0450d06b27cd81375a67d85bbe34e44acec19723dd1ffaff3f321f3f43ebddcc7f8a8d16b93c22a76302ca76d2d0c62d58891166d0ec1caead72ff2119743809cdf7aea6bba1b1ff67e9ab6ee5a355fb1004e6f565c3b1148121a229cb6fe2b5162876c446e00fb0148899ff3d9d586f3e4197fc2f19f153decf45304a0032e5bb7290ea366531839db857b5aa457939ae26332bbba4a97eba6dd023b1&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b53df0810>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:06:16,118 ERROR   wandb-upload_1:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2460'}
2025-04-07 21:06:16,118 ERROR   wandb-upload_1:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:06:16,323 ERROR   wandb-upload_3:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/output.log?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=24eb4c9fc320948f627062372cbd21890115580d40d5675aa252ea01633098c59efd337a5479c0f79b37765aefdba1fccd6a08f0634ccd2796fd00d8dde139686ac64f4a4377ec0a0b891a0aeca87534b08bf6fccc84c1ffd2fa71b2292fe0932dfebb848a641fb796935b31c7273ff8853fab0e4fb3ec41925714925eb4bdd39978ad67027f4a224015a6da56e932c4cc96de7010f38aa2e50450db0a3428dfe6f9c6eebbb8e72274355938840588425a0ed1c53d717ba0c33ab30000a1afc610379574f4e34f93e4ed6a50fea25888ff902e5dd608a3adba48a4ff3dfdeed6e288676384816b641099b7e01177bbd8504074928e7fbde97950fba0d6b5eac9&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/output.log?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=24eb4c9fc320948f627062372cbd21890115580d40d5675aa252ea01633098c59efd337a5479c0f79b37765aefdba1fccd6a08f0634ccd2796fd00d8dde139686ac64f4a4377ec0a0b891a0aeca87534b08bf6fccc84c1ffd2fa71b2292fe0932dfebb848a641fb796935b31c7273ff8853fab0e4fb3ec41925714925eb4bdd39978ad67027f4a224015a6da56e932c4cc96de7010f38aa2e50450db0a3428dfe6f9c6eebbb8e72274355938840588425a0ed1c53d717ba0c33ab30000a1afc610379574f4e34f93e4ed6a50fea25888ff902e5dd608a3adba48a4ff3dfdeed6e288676384816b641099b7e01177bbd8504074928e7fbde97950fba0d6b5eac9&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b51920290>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:06:16,323 ERROR   wandb-upload_3:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2025-04-07 21:06:16,323 ERROR   wandb-upload_3:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:06:16,327 ERROR   wandb-upload_2:1332309 [internal_api.py:upload_file():2847] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/requirements.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=225efac809eea3eda4a41c57b391208bbaae3f2ae41e41ea0ce5fe209d21696acfa4ff467c1a346113a732eb012b7457be9db0be4cb517742450a7a38d0c64c93eff43b489a66ce879558c882624410571bf7b40a45b890f87696b17f511695991880fb134d43ddd0b073ac4825a753f81628dcb01968ebadc81d1b982392972443f1ac57981e1b1a1cd197539939570b1b66bb6c52cb1955e26c5e39153b92b2057dda4fb0119f7292128e793d0c37c5fefc42b9d62f75eb8b1322f1975aa33f35adf45b63c41cbe7c0b2e6f839415ba2a4c4911fd880b0c85f53ab4a0bd41ad7ca14a5c76bd3b402a8056382b09ebe7d576a9e0729ee4034495f16e300b294&X-Goog-SignedHeaders=host&X-User=luis-carretero: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/luis-carretero-eth-zurich/GenCFD/bfcmw573/requirements.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com%2F20250407%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250407T190559Z&X-Goog-Expires=86399&X-Goog-Signature=225efac809eea3eda4a41c57b391208bbaae3f2ae41e41ea0ce5fe209d21696acfa4ff467c1a346113a732eb012b7457be9db0be4cb517742450a7a38d0c64c93eff43b489a66ce879558c882624410571bf7b40a45b890f87696b17f511695991880fb134d43ddd0b073ac4825a753f81628dcb01968ebadc81d1b982392972443f1ac57981e1b1a1cd197539939570b1b66bb6c52cb1955e26c5e39153b92b2057dda4fb0119f7292128e793d0c37c5fefc42b9d62f75eb8b1322f1975aa33f35adf45b63c41cbe7c0b2e6f839415ba2a4c4911fd880b0c85f53ab4a0bd41ad7ca14a5c76bd3b402a8056382b09ebe7d576a9e0729ee4034495f16e300b294&X-Goog-SignedHeaders=host&X-User=luis-carretero (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x149b51921090>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-07 21:06:16,327 ERROR   wandb-upload_2:1332309 [internal_api.py:upload_file():2849] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6791'}
2025-04-07 21:06:16,327 ERROR   wandb-upload_2:1332309 [internal_api.py:upload_file():2851] upload_file response body: 
2025-04-07 21:06:17,041 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:17,042 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:18,042 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:18,042 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:19,043 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:19,043 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:06:19,043 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:20,044 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:20,044 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:21,044 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:21,044 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:22,045 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:22,045 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:23,045 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:23,046 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:24,046 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:24,047 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:06:24,047 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:25,047 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:25,048 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:26,048 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:26,049 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:27,049 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:27,050 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:28,050 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:28,051 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:29,051 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:29,051 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: status_report
2025-04-07 21:06:29,052 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:30,052 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:30,052 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:31,052 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:31,053 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:32,053 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:32,054 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
2025-04-07 21:06:33,054 DEBUG   HandlerThread:1332309 [handler.py:handle_request():158] handle_request: poll_exit
2025-04-07 21:06:33,055 DEBUG   SenderThread:1332309 [sender.py:send_request():406] send_request: poll_exit
